"""Versioned Codex App Server method registry.

The App Server protocol is generated by the installed Codex CLI, but Helios's
CI intentionally has no Codex binary.  ``docs/protocol`` therefore contains a
compact generated method manifest.  The registry below classifies every
server-to-client method in that manifest so an upgrade has three explicit
outcomes:

* handled -- Helios consumes the method;
* ignored -- the method belongs to a surface Helios deliberately does not use;
* unsupported -- the method can affect an active session, but Helios does not
  yet project it and must report that limitation.

Only a method absent from the generated schema is protocol drift.  Keep this
module GTK-free so the manifest/registry contract runs in python-slim CI.
"""

from __future__ import annotations

from typing import Literal

from helios.backend.process import codex_app_events


CODEX_PROTOCOL_VERSION = "0.152.0"

NotificationDisposition = Literal["handled", "ignored", "unsupported", "unknown"]
ServerRequestDisposition = Literal["supported", "denied", "unknown"]

# Driver-level handlers that sit outside CodexAppEventAccumulator.
DRIVER_HANDLED_NOTIFICATION_METHODS: frozenset[str] = frozenset(
    {
        "configWarning",
        "deprecationNotice",
        "guardianWarning",
        "mcpServer/startupStatus/updated",
        "serverRequest/resolved",
        "thread/goal/cleared",
        "thread/goal/updated",
        "thread/compacted",
        "thread/started",
        "warning",
    }
)

HANDLED_NOTIFICATION_METHODS: frozenset[str] = frozenset(
    codex_app_events.HANDLED_NOTIFICATION_METHODS
    | DRIVER_HANDLED_NOTIFICATION_METHODS
)

# These surfaces are not initiated or owned by Helios, or duplicate state for
# which Helios already has a more specific provider event.  Ignoring them is a
# deliberate compatibility decision, not a missing handler.
IGNORED_NOTIFICATION_METHODS: frozenset[str] = frozenset(
    {
        # Account/app authentication and catalog flows are owned by Codex CLI.
        "account/login/completed",
        "account/updated",
        "app/list/updated",
        "mcpServer/oauthLogin/completed",
        # Standalone command, filesystem, process, search, project, import,
        # remote-control, and event-stream APIs are never invoked by Helios.
        "command/exec/outputDelta",
        "externalAgentConfig/import/completed",
        "externalAgentConfig/import/progress",
        "fs/changed",
        "fuzzyFileSearch/sessionCompleted",
        "fuzzyFileSearch/sessionUpdated",
        "mcpServer/event/stream/notification",
        "process/exited",
        "process/outputDelta",
        "project/changed",
        "remoteControl/status/changed",
        # Helios owns local metadata and its own durable queue. Native thread
        # status is redundant with turn lifecycle notifications.
        "thread/environment/connected",
        "thread/environment/disconnected",
        "thread/name/updated",
        "thread/project/updated",
        "thread/queue/changed",
        "thread/settings/updated",
        "thread/status/changed",
        # Realtime/audio sessions are not a Helios provider surface.
        "thread/realtime/closed",
        "thread/realtime/error",
        "thread/realtime/item/completed",
        "thread/realtime/item/started",
        "thread/realtime/item/transcript/delta",
        "thread/realtime/itemAdded",
        "thread/realtime/outputAudio/delta",
        "thread/realtime/sdp",
        "thread/realtime/started",
        "thread/realtime/transcript/delta",
        "thread/realtime/transcript/done",
        # A Windows-only setup completion cannot affect this Ubuntu client.
        "windowsSandbox/setupCompleted",
    }
)

# User-visible or safety-relevant events for which silently doing nothing would
# overstate parity.  Values are concise consequences suitable for the existing
# capability report signal.
UNSUPPORTED_NOTIFICATION_METHODS: dict[str, str] = {
    "autoApprovalReview/strictReviewRequired": (
        "strict auto-approval review state is not represented"
    ),
    "hook/completed": "native hook activity is not represented",
    "hook/started": "native hook activity is not represented",
    "item/autoApprovalReview/completed": (
        "auto-approval review activity is not represented"
    ),
    "item/autoApprovalReview/started": (
        "auto-approval review activity is not represented"
    ),
    "item/commandExecution/terminalInteraction": (
        "interactive terminal input is not supported"
    ),
    "model/rerouted": "provider model rerouting is not reflected in the transcript",
    "model/safetyBuffering/updated": (
        "provider safety-buffering state is not represented"
    ),
    "model/verification": "provider model verification state is not represented",
    "modelProvider/authRecoveryCompleted": (
        "model-provider authentication recovery state is not displayed"
    ),
    "modelProvider/authRecoveryStarted": (
        "model-provider authentication recovery state is not displayed"
    ),
    "skills/changed": "Codex skill inventory changes are not refreshed in Helios",
    "thread/archived": "native thread archival is not reconciled into Helios",
    "thread/closed": "native thread closure is not reconciled into Helios",
    "thread/deleted": "native thread deletion is not reconciled into Helios",
    "thread/reverted": "native thread reverts are not reconciled into Helios",
    "thread/unarchived": "native thread archival is not reconciled into Helios",
    "turn/moderationMetadata": "turn moderation metadata is not displayed",
    "windows/worldWritableWarning": (
        "Codex workspace safety warnings are not displayed"
    ),
}

KNOWN_NOTIFICATION_METHODS: frozenset[str] = frozenset(
    HANDLED_NOTIFICATION_METHODS
    | IGNORED_NOTIFICATION_METHODS
    | UNSUPPORTED_NOTIFICATION_METHODS.keys()
)

# Requests Helios answers with the generated response contract.
SUPPORTED_SERVER_REQUEST_METHODS: frozenset[str] = frozenset(
    {
        "item/commandExecution/requestApproval",
        "item/fileChange/requestApproval",
        "item/permissions/requestApproval",
        "item/tool/call",
        "item/tool/requestUserInput",
        "currentTime/read",
    }
)

# These methods are known to the pinned schema but Helios intentionally does
# not grant the requested client capability.  MCP elicitation receives the
# protocol's structured decline response; the others receive a JSON-RPC error.
DENIED_SERVER_REQUEST_METHODS: dict[str, str] = {
    "account/chatgptAuthTokens/refresh": "Codex CLI owns authentication",
    "applyPatchApproval": "legacy patch approvals are not accepted",
    "attestation/generate": "client attestation is not implemented",
    "execCommandApproval": "legacy command approvals are not accepted",
    "mcpServer/elicitation/request": "MCP elicitation is not enabled in Helios",
}

KNOWN_SERVER_REQUEST_METHODS: frozenset[str] = frozenset(
    SUPPORTED_SERVER_REQUEST_METHODS | DENIED_SERVER_REQUEST_METHODS.keys()
)

# Every JSON-RPC request/notification Helios currently sends.  The schema test
# guards this list against the generated client surface; keeping the list here
# also makes the compatibility boundary reviewable without AST archaeology.
CLIENT_REQUEST_METHODS_USED: frozenset[str] = frozenset(
    {
        "account/rateLimits/read",
        "collaborationMode/list",
        "initialize",
        "mcpServerStatus/list",
        "model/list",
        "review/start",
        "thread/goal/clear",
        "thread/goal/set",
        "thread/compact/start",
        "thread/fork",
        "thread/resume",
        "thread/settings/update",
        "thread/start",
        "thread/unsubscribe",
        "turn/interrupt",
        "turn/start",
        "turn/steer",
    }
)
CLIENT_NOTIFICATION_METHODS_USED: frozenset[str] = frozenset({"initialized"})


def classify_notification(method: str) -> NotificationDisposition:
    """Return the pinned-schema disposition for one server notification."""

    if method in HANDLED_NOTIFICATION_METHODS:
        return "handled"
    if method in IGNORED_NOTIFICATION_METHODS:
        return "ignored"
    if method in UNSUPPORTED_NOTIFICATION_METHODS:
        return "unsupported"
    return "unknown"


def classify_server_request(method: str) -> ServerRequestDisposition:
    """Return the pinned-schema disposition for one server request."""

    if method in SUPPORTED_SERVER_REQUEST_METHODS:
        return "supported"
    if method in DENIED_SERVER_REQUEST_METHODS:
        return "denied"
    return "unknown"


def unsupported_notification_message(method: str) -> str:
    """Return a stable user-facing consequence for a known capability gap."""

    return UNSUPPORTED_NOTIFICATION_METHODS.get(
        method,
        f"a known Codex event is not supported ({method})",
    )
